# theme: jekyll-theme-cayman

# Site settings
title: Jasper's Blog
SEOTitle: Jasper的博客 | Jasper's Blog
header-img: img/home-bg4.jpg
email: keep_progress@163.com
description: "一点个人记录 | 人生就是不断探索"
keyword: "jasper, caixin, 一点记录, 思想感悟, 进步, Java, Java开发, AI, deep learning, 深度学习, 算法"
url: #"https://meilianwu.com/"             # your host, for absolute URL
baseurl: #""                             # for example, '/blog' if your blog hosted on 'host/blog'


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.ico


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "努力且坚定 温柔且上进"
sidebar-avatar: /img/me.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     pumpbumb
github_username:    pumpbumb


# Build settings
paginate: 10
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c86710f4bb1e75878d                            #生成的clientID
  clientSecret: 497c68a50f06bf85d1a73f4bf951fbb94a36eaa1    #生成的clientSecret
  repo: pumpbumb.github.io    #仓库名称
  owner: pumpbumb    #github用户名
  admin: pumpbumb
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
friends: [
  {
    title: "Jasper's blog",
    href: "https://pumpbumb.github.io/"
  },
  {
    title: "chenshuyao's blog",
    href: "https://chenshuyao.cn/"
  }
]
